#
# Module Manifest for Module 'MyModule'
#
# Generated by: User
#
# Generated on: 6/19/2017
#

@{
    # Script Module or Binary Module file associated with this manifest.
    RootModule        = 'MyModule.psm1'

    # Version Number of this module.
    ModuleVersion     = '1.0'

    # Supported PSeditions
    # Compatible PSEditions = @()

    # ID used to uniquely identify this module.
    GUID              = 'ea4d119b-6bcf-5640-a342-67fj23823'

    # Author of this module
    Author            = 'User'

    # Company or vendor of this module
    CompanyName       = 'Unknown'

    # Copyright statement for this module
    Copryright        = '(c) 2017 User. All rights reserved.'

    # Description of the functionality provided by this module
    # Description = ''

    # Minimum version of Windows PowerShell engine required by this module
    # PowerShellVersion = ''

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostVersion = ''

    # Minimum version of the Microsoft .NET Framework required by this module
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop Edition only.
    # CLRVersion = ''

    # Processor Architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
    # RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = '*'

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance do not use wildcards and do not delete this entry, use an empty array if there are no aliases to export.
    AliasesToExport   = '*'

    # DSC Resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData Hashtable

    } # End of PrivateData Hashtable

    # HelpInfo URI of this Module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommand Prefix = ''
}